### ISSUE TITLE
Does this come with a free spigotmc ban?

### ISSUE THREAD

**Issue by MeltedLux** [NightDevel/Attack-Helicopter#3]

**Comment by GGhosted** [comment]
1x free bane.  you will receive your baned in 22hrs

**Comment by GGhosted** [comment]
![image](https://cloud.githubusercontent.com/assets/11985930/9072786/174c57ba-3af5-11e5-9c74-4f7b9fcb8c17.png)
it's here

**Comment by SpongyBacon** [comment]
#unbanenight

**Comment by MeltedLux** [comment]
I have recieved my bane thnx @NotGGhost
